apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: lockerstock
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      organization: lockerstock
      serviceAccountName: actions-runner
